name = "HyperModularity"
uuid = "bc4352e7-2825-48c1-aa5c-95462f20dcc0"
authors = ["Nate Veldt"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
